### ISSUE TITLE
[Request?] /名前の由来.txtをREADME.mdと統合

### ISSUE THREAD

**Issue by Sorakime** [Mf-3d/Flune-Browser#1]
いつもお世話になっておりますSorakimeです。
このリポジトリの `名前の由来.txt` は `README.md` にまとめてしまってはいかがでしょうか。

提案理由としては、

- そっちの方が見やすい
- 日本語の文字が含まれたテキストファイルは何かと厄介

といったことが挙げられます。

ご検討よろしくお願いします

**Comment by Mf-3d** [comment]
承知しました。

**Comment by Mf-3d** [comment]
直しておきました。
