### ISSUE TITLE
レビューしてみたよ

### ISSUE THREAD

**Issue by Sorakime** [Mf-3d/Flune-Browser#3]
毎度毎度のことこちらのFluneをレビューさせて頂いておりますけれども。今回からはこのIssueに書き込ませていだたきますねっ！

# オフライン時
オフライン時ねぇ。これみた感じFontAwesomeに依存してる感じですか、えぇ。
それが理由なんやけどWi-Fiが落とされてたらアイコン表示されないのはなぁ...一応スタンドアローンアプリとしては致命的なんじゃないかなぁって思う。
<img src="https://user-images.githubusercontent.com/69241694/175544717-37364d87-a2df-49b5-a152-bf20740e36ba.png">

# ちょっと動作が、、
サクサク感がない。ソフトウェアの動き、挙動の話ね。重量は測ってないんだけど、体感速度もうちょっと上げてほしいかな。アニメーションを追加したり処理の最適化をして速く動けるようにしたり。

# こいつ最高
Monotでも実装してもええねんけどめんどくさいとか必要性がないとかそう言うので実装してないこいつ。
<img width="84" alt="スクリーンショット 2022-06-24 22 32 04" src="https://user-images.githubusercontent.com/69241694/175546368-fd58f9b5-42d3-4cbb-a51a-72c05dc381a2.png">

# scrollBounce...
BrowserView。scrollBounce: trueになってないみたいなのが個人的には気に食わないなぁ。これって、macOSのみで動作する、ページの端に行ってもちょっとスクロールできる的なやつのことなんよ。こういうね。
これができないのがねぇという。
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/69241694/175546971-9a0aa980-56fc-48f0-8e07-d806712014c1.png">

# ピンチイン・ピンチアウト
ピンチは何気によく使うので実装されてないのは使いにくいかなぁ。これ、dom-readyとかのタイミングで適当にwebFrame.setVisualZoomLevelLimits()で実装できちゃうから、これはやってほしい。ちなみにどうやら拡大率はいくらでもでかくできるらしくて、僕が普段パソコンでMisskey使う時用に作ったデスクトップクライアントさん、こいつは確か1000倍くらいまでピンチインできるようにしてる。1未満は指定できなかった気がする
https://www.electronjs.org/ja/docs/latest/api/web-frame#webframesetvisualzoomlevellimitsminimumlevel-maximumlevel
<img width="1912" alt="スクリーンショット 2022-06-24 22 42 33" src="https://user-images.githubusercontent.com/69241694/175548243-573c0f2e-e641-4267-b50a-2bf9d540d37b.png">

# ダークモードです....
ダークモードでも容赦なく読み込み時明るいふうに表示されると目が、、、目がっ！！！
一応Monotさん、ダークモードならダークになるように実装してあるのでね.... 
<img width="1534" alt="スクリーンショット 2022-06-24 22 38 32" src="https://user-images.githubusercontent.com/69241694/175547505-4a1276fb-e9a4-4609-9670-2e82320f1e34.png">

# 目が（二回目）
```js
win.on('ready-to-show', () => {
  win.show();
});
```
で、どうぞ
<img width="1534" alt="スクリーンショット 2022-06-24 22 43 38" src="https://user-images.githubusercontent.com/69241694/175548455-8c60f504-ed14-413e-96a9-9dc0e4cb6ca1.png">

# 起動速度
遅いのでなんとかしてくださーい。Chromeの初回起動よりは少し速いけど。ちなみに一回取り直してるから実は十回くらい起動してる。Fluneの初回起動は10秒弱くらい時間かかったっけな
Flastとはアプリの起動速度自体は変わらないかな。Flastの方が起動してからの処理に時間がかかってるけど

https://user-images.githubusercontent.com/69241694/175550193-9641633a-475e-4c9a-907d-91eebaace83a.mov

以上でーす
あー後アイコンは良い感じ。Macぽさがある
<img width="1553" alt="スクリーンショット 2022-06-24 23 01 31" src="https://user-images.githubusercontent.com/69241694/175551734-94b2be9e-c479-4dd3-832b-9224a68d75e0.png">

**Comment by Mf-3d** [comment]
レビューありがとうございます！

> ピンチイン・ピンチアウト

2.2.0で実装しますかね。

> 起動速度

うーん...🤔
まぁホーム画面の読み込みが遅いのもあるかもしれません...。

> ダークモードです....

2.2.0で実装します。

> scrollBounce...

いるのかね...
(まあ実装してみます)

> ちょっと動作が、、

うーん...そうですねぇ

> オフライン時

それはFontAwesomeの使用上無理です...
あとTwemojiもですよね...

**Comment by Sorakime** [comment]
だからFontAwesomeから脱却しません、、？()()
twemojiはまぁしゃーなし（）

**Comment by Mf-3d** [comment]
FontAwesomeは大好きだし...

**Comment by Mf-3d** [comment]
えっとFontAwesomeと目が(二回目)以外修正しました。

**Comment by Sorakime** [comment]
👍

**Comment by Mf-3d** [comment]
矢部

**Comment by Sorakime** [comment]
薮

**Comment by Sorakime** [comment]
クローズしよう
